# Generated by Django 4.1.10 on 2024-03-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=25)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=20)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=19)),
                ('company_id', models.IntegerField()),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
